/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.cli

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertNotNull(App.appName, "Kotlin CLI App")
        assertNotNull(App.version, "0.0.1")
    }
}